name: Hello world!

on:
  push:
    branches:
      - master

jobs: 
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: | 
          echo "Hello World!"
      - name: Say current date
        run: | 
          echo date
      - name: list directories
        run: |
          echo ls